### PR TITLE
Implementing Bluedog DB

### PR DESCRIPTION
**Pull request by Gordon-Dry**
Testing, don't merge yet

### CODE REVIEW

**Comment by madman2003** [comment]
You misunderstood the way "brute force" works, it simply only creates one set of tank configs. And gives every B9 tank access to those. All the typos i pushed mentioning you name in the commit.

**Comment by madman2003** [comment]
But definitely thanks for trying and helping out ;-)

**Comment by Gordon-Dry** [comment]
Well, Bluedog DB got its own dedicated tank types ...

**Comment by madman2003** [comment]
But does it make a big difference? I understand costs need to be looked at, but in my book a tank just has X volume (decided by mod) and then you can put stuff in that volume. But I'm glad to know where my assumptions break down, then I'd have a good reason for more complex patching approaches.

**Comment by Gordon-Dry** [comment]
I just launched the first BDB vessel in new career without hassle - with my branch.

**Pull request closed without merging**
